{{- if .Values.auth.manageRpcSecret }}
{{- if not .Values.auth.rpcPassword }}{{ fail "auth.rpcPassword is required when manageRpcSecret=true" }}{{ end }}
apiVersion: v1
kind: Secret
metadata:
  name: bitcoind-rpc
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  rpc-password: {{ .Values.auth.rpcPassword | quote }}
{{- end }}
