apiVersion: v1
kind: Service
metadata:
  name: bitcoind
spec:
  selector:
    app.kubernetes.io/name: bitcoind
  ports:
    - { name: rpc, port: 18443, targetPort: rpc }
    - { name: p2p, port: 18444, targetPort: p2p }
    - { name: zmqblock, port: 28332, targetPort: zmqblock }
    - { name: zmqtx, port: 28333, targetPort: zmqtx }
