import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
test('validation and provenance workflows keep verification and signing responsibilities separate', () => {
  const validation = readFileSync('.github/workflows/validate.yml', 'utf8');
  const provenance = readFileSync('.github/workflows/attest-source-provenance.yml', 'utf8');
  assert.match(validation, /name: Validate/);
  assert.match(validation, /name: Repository verification/);
  assert.match(validation, /run: scripts\/ci-verify\.sh/);
  assert.doesNotMatch(validation, /id-token: write/);
  assert.match(provenance, /name: Attest Source Provenance/);
  assert.match(provenance, /workflow_run:/);
  assert.match(provenance, /workflows: \[Validate\]/);
  assert.match(provenance, /github\.event\.workflow_run\.conclusion == 'success'/);
  assert.match(provenance, /github\.event\.workflow_run\.head_sha/);
  assert.match(provenance, /sigstore\/cosign-installer@[0-9a-f]{40}/);
  assert.match(provenance, /id-token: write/);
  assert.match(provenance, /cosign sign-blob --yes/);
  const verifier = readFileSync('scripts/verify-ci-provenance.sh', 'utf8');
  assert.match(verifier, /--certificate-oidc-issuer 'https:\/\/token\.actions\.githubusercontent\.com'/);
  assert.match(verifier, /github\.com\/\$\{repository\}\/.github\/workflows\/attest-source-provenance\.yml@refs\/heads\/main/);
  const phase7 = readFileSync('.github/workflows/phase7-image-evidence.yml', 'utf8');
  assert.match(phase7, /packages: write/);
  assert.match(phase7, /id-token: write/);
  assert.match(phase7, /COSIGN_REPOSITORY: ghcr\.io\/s1ns3nz0\/ln-ssdf-evidence/);
  assert.match(phase7, /PHASE7_VSA_GATE_MODE: diagnostic/);
  const scorecards = readFileSync('.github/workflows/measure-upstream-scorecards.yml', 'utf8');
  assert.match(scorecards, /lightningnetwork\/lnd/);
  assert.match(scorecards, /lightninglabs\/aperture/);
  assert.match(scorecards, /ghcr\.io\/ossf\/scorecard@sha256:[0-9a-f]{64}/);
  assert.match(scorecards, /--format json/);
  assert.match(scorecards, /actions\/upload-artifact@[0-9a-f]{40}/);
});
