apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lnd
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: "4" }
spec:
  project: default
  source:
    repoURL: git://git-server.gitops-system.svc:9418/ln-ssdf.git
    targetRevision: main
    path: charts/lnd
    helm: { releaseName: lnd }
  destination: { server: https://kubernetes.default.svc, namespace: ssdf-system }
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: lnd-primary
      namespace: ssdf-system
      jsonPointers:
        - /spec/template/metadata/annotations/vso.secrets.hashicorp.com~1restartedAt
  syncPolicy: { automated: { prune: false, selfHeal: true }, syncOptions: [CreateNamespace=true, RespectIgnoreDifferences=true] }
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: "5" }
spec:
  project: default
  source:
    repoURL: git://git-server.gitops-system.svc:9418/ln-ssdf.git
    targetRevision: main
    path: charts/observability
    helm: { releaseName: observability }
  destination: { server: https://kubernetes.default.svc, namespace: ssdf-system }
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: postgres-exporter
      namespace: ssdf-system
      jsonPointers:
        - /spec/template/metadata/annotations/vso.secrets.hashicorp.com~1restartedAt
  syncPolicy: { automated: { prune: false, selfHeal: true }, syncOptions: [CreateNamespace=true, RespectIgnoreDifferences=true] }
