apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-probe
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: "6" }
spec:
  project: default
  source:
    repoURL: git://git-server.gitops-system.svc:9418/ln-ssdf.git
    targetRevision: main
    path: gitops/probe
  destination: { server: https://kubernetes.default.svc, namespace: ssdf-system }
  syncPolicy: { automated: { prune: false, selfHeal: true }, syncOptions: [CreateNamespace=true] }
