apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ln-ssdf-postgres.fullname" . }}-init
  labels:
    app.kubernetes.io/name: {{ include "ln-ssdf-postgres.name" . }}
data:
  00-create-databases.sql: |
    CREATE DATABASE lnd;
    CREATE DATABASE ssdf;
