apiVersion: v1
kind: Service
metadata:
  name: {{ include "ln-ssdf-postgres.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ln-ssdf-postgres.name" . }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "ln-ssdf-postgres.name" . }}
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
