apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ln-ssdf-vault.fullname" . }}-config
data:
  vault.hcl: |
    ui = false
    disable_mlock = true

    listener "tcp" {
      address = "[::]:8200"
      cluster_address = "[::]:8201"
      tls_disable = 1
    }

    storage "raft" {
      path = "/vault/data"
      node_id = "{{ include "ln-ssdf-vault.fullname" . }}"
    }

    api_addr = "http://{{ include "ln-ssdf-vault.fullname" . }}.{{ .Release.Namespace }}.svc:8200"
    cluster_addr = "http://{{ include "ln-ssdf-vault.fullname" . }}-0.{{ include "ln-ssdf-vault.fullname" . }}-internal.{{ .Release.Namespace }}.svc:8201"
